# TODO: On PRs, check for a modified changelog.mdx file or "bypass changelog" label. If neither exist, fail. If one exists, pass
name: Changelog
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  changelog:
    name: Enforce Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check Changelog
        run: bash ci/changelog.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PULL_TITLE: ${{ github.event.pull_request.title }}
